# Generated by Django 5.0.6 on 2024-06-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc360user',
            name='name',
        ),
        migrations.AddField(
            model_name='doc360user',
            name='date_brith',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc360user',
            name='id_nationality',
            field=models.IntegerField(default=0),
        ),
    ]
