# Generated by Django 5.0.6 on 2024-05-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='status',
            field=models.CharField(choices=[('P', 'PENDIENTE'), ('A', 'ACTIVO'), ('I', 'INACTIVO')], default='P', max_length=1),
        ),
    ]
