# Generated by Django 5.0.6 on 2024-06-05 14:04

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='user_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
