# Generated by Django 5.0.6 on 2024-06-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apiuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='date_brith',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
