# Generated by Django 5.0.6 on 2024-06-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apiuser_date_brith_alter_apiuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='id_nationality',
            field=models.IntegerField(default=0),
        ),
    ]
