# Generated by Django 5.0.6 on 2024-06-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_apiuser_id_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
