# Generated by Django 5.0.6 on 2024-06-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_apiuser_email_alter_apiuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='username',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
