# Generated by Django 5.0.6 on 2024-05-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.PositiveIntegerField()),
                ('add_datetime', models.DateTimeField()),
                ('speciality', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('public', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'medical_history',
                'verbose_name_plural': 'medical_histories',
                'db_table': 'medical_histories',
            },
        ),
    ]
