# Generated by Django 5.0.6 on 2024-05-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medics_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicprofile',
            name='status',
            field=models.CharField(choices=[('P', 'PENDIENTE'), ('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1),
        ),
    ]
